/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ssu.task.config;

//import io.qameta.allure.Feature;
//import io.qameta.allure.Story;

import io.github.bonigarcia.wdm.WebDriverManager;
import lombok.extern.slf4j.Slf4j;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Parameters;

@Slf4j
public class BaseTest {
    protected static WebDriver driver;

    // TODO: вынести в файл конфигурации и брать потом оттуда
    private final String site = "https://artnow.ru/";

    @BeforeClass(description = "Start webdriver, set up browser")
    @Parameters(value = "browser")
    public void setup(String browser) {
        log.info("Starting browser setup for {}", browser);
        log.info("Using site: {}", site);
        log.info("Selected browser: {}", browser);

        if (browser.equalsIgnoreCase("firefox")) {
            log.info("Setting up Firefox driver...");
            driver = new FirefoxDriver();
            WebDriverManager.firefoxdriver().setup();
        } else if (browser.equalsIgnoreCase("chrome")) {
            log.info("Setting up Chrome driver...");
            driver = new ChromeDriver();
            WebDriverManager.chromedriver().setup();
        } else {
            throw new IllegalCallerException("You need to add a specific browser in the configurations");
        }

        log.info("Navigating to site: {}", site);
        driver.get(site);
    }

    @AfterClass(description = "Stop browser")
    public void stopMethod() {
        driver.quit();
        log.info("Browser successfully quited.");
    }
}